### ISSUE TITLE
Can't compile. no map_tacplus_user.h

### ISSUE THREAD

**Issue by stevetavve** [daveolson53/pam_tacplus#1]
When I attempt to compile I am getting the following error:

```
[15:18:08 slanglois@tron pam_tacplus-master]$ make
make  all-am
make[1]: Entering directory `/home/slanglois/Downloads/pam_tacplus-master'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fstack-protector-all -Wl,-z,relro -Wl,-z,now -fPIE -pie -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I ./libtac/include -g -O2 -MT pam_tacplus_la-pam_tacplus.lo -MD -MP -MF .deps/pam_tacplus_la-pam_tacplus.Tpo -c -o pam_tacplus_la-pam_tacplus.lo `test -f 'pam_tacplus.c' || echo './'`pam_tacplus.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fstack-protector-all -Wl,-z,relro -Wl,-z,now -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I ./libtac/include -g -O2 -MT pam_tacplus_la-pam_tacplus.lo -MD -MP -MF .deps/pam_tacplus_la-pam_tacplus.Tpo -c pam_tacplus.c  -fPIC -DPIC -o .libs/pam_tacplus_la-pam_tacplus.o
pam_tacplus.c:42:38: fatal error: tacplus/map_tacplus_user.h: No such file or directory
 #include <tacplus/map_tacplus_user.h>
                                      ^
compilation terminated.
make[1]: *** [pam_tacplus_la-pam_tacplus.lo] Error 1
make[1]: Leaving directory `/home/slanglois/Downloads/pam_tacplus-master'
make: *** [all] Error 2

```
Looking at the other modules I saw that there is a a map_tacplus_user.h file in libtacplus-map-master so I download that but when I compile it, it complains about libaudit.h which I cannot find in any of the related git modules, audisp-tacplus, libtacplus-map, libnss-tacplus, and pam-tacplus.

```
[15:12:12 slanglois@tron libtacplus-map-master]$ make
make: Warning: File `.deps/libtacplus_map_la-map_tacplus_user.Plo' has modification time 72 s in the future
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/slanglois/Downloads/pam_tacplus-master/libtacplus-map-master/config/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-am
make[1]: Entering directory `/home/slanglois/Downloads/pam_tacplus-master/libtacplus-map-master'
make[1]: Warning: File `.deps/libtacplus_map_la-map_tacplus_user.Plo' has modification time 72 s in the future
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -Ilibtac/include -g -O2 -Wall -Werror -MT libtacplus_map_la-map_tacplus_user.lo -MD -MP -MF .deps/libtacplus_map_la-map_tacplus_user.Tpo -c -o libtacplus_map_la-map_tacplus_user.lo `test -f 'map_tacplus_user.c' || echo './'`map_tacplus_user.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Ilibtac/include -g -O2 -Wall -Werror -MT libtacplus_map_la-map_tacplus_user.lo -MD -MP -MF .deps/libtacplus_map_la-map_tacplus_user.Tpo -c map_tacplus_user.c  -fPIC -DPIC -o .libs/libtacplus_map_la-map_tacplus_user.o
map_tacplus_user.c:26:22: fatal error: libaudit.h: No such file or directory
 #include <libaudit.h>
                      ^
compilation terminated.
make[1]: *** [libtacplus_map_la-map_tacplus_user.lo] Error 1
make[1]: Leaving directory `/home/slanglois/Downloads/pam_tacplus-master/libtacplus-map-master'
make: *** [all] Error 2

```
Any help with this is greatly appreciated. Thanks.

**Comment by daveolson53** [comment]
stevetavve <notifications@github.com> wrote:

> When I attempt to compile I am getting the following error:
> 
> [15:18:08 slanglois@tron pam_tacplus-master]$ make
> make all-am
> make[1]: Entering directory /home/slanglois/Downloads/pam_tacplus-master' /bin/
> sh ./libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I.
> -fstack-protector-all -Wl,-z,relro -Wl,-z,now -fPIE -pie -U_FORTIFY_SOURCE
> -D_FORTIFY_SOURCE=2 -I ./libtac/include -g -O2 -MT
> pam_tacplus_la-pam_tacplus.lo -MD -MP -MF .deps/pam_tacplus_la-pam_tacplus.Tpo
> -c -o pam_tacplus_la-pam_tacplus.lotest -f 'pam_tacplus.c' || echo './
> 'pam_tacplus.c libtool: compile: gcc -DHAVE_CONFIG_H -I. -fstack-protector-all
> -Wl,-z,relro -Wl,-z,now -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I ./libtac/
> include -g -O2 -MT pam_tacplus_la-pam_tacplus.lo -MD -MP -MF .deps/
> pam_tacplus_la-pam_tacplus.Tpo -c pam_tacplus.c -fPIC -DPIC -o .libs/
> pam_tacplus_la-pam_tacplus.o pam_tacplus.c:42:38: fatal error: tacplus/
> map_tacplus_user.h: No such file or directory #include <tacplus/
> map_tacplus_user.h> ^ compilation terminated. make[1]: ***
> [pam_tacplus_la-pam_tacplus.lo] Error 1 make[1]: Leaving directory/home/
> slanglois/Downloads/pam_tacplus-master'
> make: *** [all] Error 2
> 
> Looking at the other modules I saw that there is a a map_tacplus_user.h file in
> libtacplus-map-master so I download that but when I compile it, it complains
> about libaudit.h which I cannot find in any of the related git modules,
> audisp-tacplus, libtacplus-map, libnss-tacplus, and pam-tacplus.

libaudit-dev on debian, probably the same on other linux distributions.

For my packages, you can look at debian/control to see the build dependencies.

And yes, you need to build libtacplus-map first, and install at least
the -dev package (or the files that go into it, if you aren't on
debian).

I have some other changes pending to my modified packages that add a few
features, and some bug fixes.   I've not gotten around to pushing those
to github yet.  I'll probably get to that next week, after some more
testing.


Dave Olson
olson@cumulusnetworks.com

**Comment by daveolson53** [comment]
project inactive.  Mostly a build documentation issue.
