### ISSUE TITLE
configure.ac:36: error: possibly undefined macro: AC_CHECK_LIB

### ISSUE THREAD

**Issue by alextomko** [daveolson53/pam_tacplus#3]
If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:48: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by yoriyatana** [comment]
I also have the same error.

**Comment by daveolson53** [comment]
Tung Nguyen <notifications@github.com> wrote:

> I also have the same error.

This most commonly seems to be caused by not having all the required
tools installed.

What distro, and what were your steps to get to the error?

Dave Olson
olson@cumulusnetworks.com

**Comment by yoriyatana** [comment]
My Machine uses Centos 7 (minimum fresh install). I updated every currently installed package and installed a group of "Developement Tools" via yum.
Then I  cloned the source code, ran "./auto.sh" and the error appeared.

**Comment by daveolson53** [comment]
Tung Nguyen <notifications@github.com> wrote:

> My Machine uses Centos 7 (minimum fresh install). I updated every currently
> installed package and installed a group of "Developement Tools" via yum.
> Then I cloned the source code, ran "./auto.sh" and the error appeared.

The most common cause of this seems to be missing pkg-config (that's
what it's called on debian, I forget what it is on redhat/fedora).

Dave Olson
olson@cumulusnetworks.com

**Comment by hutchisr** [comment]
Still have this issue on Ubuntu 19.04 even after installing pkg-config.

**Comment by Slap37** [comment]
Having the same issue when running ./auto.sh in RHEL 7.5:

`configure.ac:36: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:48: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1`

I was able to install other versions of this package successfully but i wanted to try this one to use your libnss-tacplus

**Comment by daveolson53** [comment]
Slap37 <notifications@github.com> wrote:

> Having the same issue when running ./auto.sh in RHEL 7.5:
> 
> configure.ac:36: error: possibly undefined macro: AC_CHECK_LIB If this token
> and others are legitimate, please use m4_pattern_allow. See the Autoconf
> documentation. configure.ac:47: error: possibly undefined macro:
> AC_CHECK_HEADERS configure.ac:48: error: possibly undefined macro: AC_MSG_ERROR
> autoreconf: /usr/bin/autoconf failed with exit status: 1
> 
> I was able to install other versions of this package successfully but i wanted
> to try this one to use your libnss-tacplus

I've seen this when you are on a fairly different version than the
version that was last built.  Usually running ./auto.sh to rebuild
the auto tools versions fixes it.

If not, it's more painful to track down.

Dave Olson
olson@cumulusnetworks.com

**Comment by idefixcert** [comment]
im my case it was libssl-dev which had to be installed

**Comment by bacharya** [comment]
I have faced similar issue and upon installing "autoconf-archive" on debian it got resolved.
