### ISSUE TITLE
Error on checks

### ISSUE THREAD

**Issue by philipathomas** [daveolson53/pam_tacplus#4]
Hi, 

Got a lovely error: 

`checking for select... yes`
`checking for socket... yes`
`checking for logwtmp... yes`
`./configure: line 9491: syntax error near unexpected token newline'
./configure: line 9491:            AX_CHECK_OPENSSL('`

Running a newer Ubuntu build " VERSION="19.10 (Eoan Ermine)"

Any thoughts?

Thanks, Phil

**Comment by paddyvgc** [comment]
Running ./auto.sh throws the below error:

autoreconf: running: /usr/bin/autoconf --force
configure.ac:36: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:48: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1

Any help is appreciated

**Comment by daveolson53** [comment]
Sorry, don't remember encountering this, but a number of configuration issues I had were due to not having a completely clean directory first.  This is no longer an active project for me.
